databases:
  - name: servidorAmazingTeam
    plan: free
    databaseName: amazingbdd
    user: xavier

services:
  - type: web
    name: amazingTeam
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn amazingTeam.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorAmazingTeam
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: amazing-team.onrender.com

# set DATABASE_URL=postgresql://xavier:o48UmMNx4AYjKac7JhFmmKvs6lIPCe4w@dpg-cqp1q3lds78s73e2oq0g-a.oregon-postgres.render.com/amazingbdd