# Generated by Django 5.0.6 on 2024-07-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primerNombre', models.CharField(max_length=30)),
                ('segundoNombre', models.CharField(max_length=30)),
                ('apellidoPaterno', models.CharField(max_length=30)),
                ('apellidoMaterno', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('fotografia', models.FileField(blank=True, null=True, upload_to='usuarios')),
                ('email', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=15)),
            ],
        ),
    ]
